"""Alteração na tabela Fornecedor

Revision ID: 1512c5b0a643
Revises: 869df7cb56aa
Create Date: 2024-01-29 11:55:40.888033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1512c5b0a643'
down_revision: Union[str, None] = '869df7cb56aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
