"""Cria relacionamento entre fornecedor e conta

Revision ID: 869df7cb56aa
Revises: 87b7caeea03e
Create Date: 2024-01-29 11:11:50.460907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '869df7cb56aa'
down_revision: Union[str, None] = '87b7caeea03e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contas_a_pagar_receber', sa.Column('fornecedor_cliente_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'contas_a_pagar_receber', 'fornecedor_cliente', ['fornecedor_cliente_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contas_a_pagar_receber', type_='foreignkey')
    op.drop_column('contas_a_pagar_receber', 'fornecedor_cliente_id')
    # ### end Alembic commands ###
