"""Cria tabela fornecedor cliente

Revision ID: 87b7caeea03e
Revises: 
Create Date: 2024-01-27 15:57:55.365790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b7caeea03e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedor_cliente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('contas_a_pagar_receber', 'valor',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contas_a_pagar_receber', 'valor',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.drop_table('fornecedor_cliente')
    # ### end Alembic commands ###
